### ISSUE TITLE
[Bug]: `config apply-patch` fail with error info "All Keys are not parsed in MUX_LINKMGR"

### ISSUE THREAD

**Issue by weiguo-nvidia** [sonic-net/sonic-mgmt#13711]
### Issue Description

The dual tor test case `tests/bgp/test_bgp_dual_asn.py::test_bgp_dual_asn_v4` fail because execute command `config apply-patch /tmp/tmp.LgQ3s0vSw7` report error info `All Keys are not parsed in MUX_LINKMGR`

The issue might related to PR https://github.com/sonic-net/sonic-mgmt/pull/13004, it disable the timed oscillation by `'sonic-db-cli CONFIG_DB HSET "MUX_LINKMGR|TIMED_OSCILLATION" "oscillation_enabled" "false"'`

Before the PR change, the same case could pass

### Results you see

1. This is the test file content
```
admin@router:~$ sudo cat /tmp/tmp.LgQ3s0vSw7
[
    {
        "op": "add",
        "path": "/BGP_PEER_RANGE",
        "value": {
            "BGPSLBPassive": {
                "ip_range": [
                    "192.168.0.0/22"
                ],
                "name": "BGPSLBPassive",
                "src_address": "10.1.0.33",
                "peer_asn": "64523"
            },
            "BGPSLBPassiveV6": {
                "ip_range": [
                    "fc02:1000::/65"
                ],
                "name": "BGPSLBPassiveV6",
                "src_address": "fc00:1::33",
                "peer_asn": "64523"
            }
        }
    }
]
```

2. Execute command `sudo config apply-patch /tmp/tmp.LgQ3s0vSw7` on DUT to apply the test file, but it fail
```
admin@router:~$ sudo config apply-patch /tmp/tmp.LgQ3s0vSw7
Patch Applier: Patch application starting.
Patch Applier: Patch: [{"op": "add", "path": "/BGP_PEER_RANGE", "value": {"BGPSLBPassive": {"ip_range": ["192.168.0.0/22"], "name": "BGPSLBPassive", "src_address": "10.1.0.33", "peer_asn": "64523"}, "BGPSLBPassiveV6": {"ip_range": ["fc02:1000::/65"], "name": "BGPSLBPassiveV6", "src_address": "fc00:1::33", "peer_asn": "64523"}}}]
Patch Applier: Getting current config db.
Patch Applier: Simulating the target full config after applying the patch.
Patch Applier: Validating all JsonPatch operations are permitted on the specified fields
Patch Applier: Validating target config does not have empty tables, since they do not show up in ConfigDb.
Patch Applier: Sorting patch updates.
Failed to apply patch
Usage: config apply-patch [OPTIONS] PATCH_FILE_PATH
Try "config apply-patch -h" for help.

Error: Given patch will produce invalid config. Error: Data Loading Failed
All Keys are not parsed in MUX_LINKMGR
dict_keys(['TIMED_OSCILLATION'])
exceptionList:[]
```

3. Check the `oscillation` status, it is disabled by fixture `disable_timed_oscillation_active_standby`, which is introduced by PR https://github.com/sonic-net/sonic-mgmt/pull/13004
```
admin@router:~$ redis-cli -n 4 HGETALL "MUX_LINKMGR|TIMED_OSCILLATION"
1) "oscillation_enabled"
2) "false"
```

### Results you expected to see

Test case pass

### Is it platform specific

generic

**Comment by bingwang-ms** [comment]
The issue has been fixed in the new image by adding the corresponding YANG model https://github.com/sonic-net/sonic-buildimage/pull/19275. Please use the image with the fix to run the test.

**Comment by weiguo-nvidia** [comment]
> The issue has been fixed in the new image by adding the corresponding YANG model [sonic-net/sonic-buildimage#19275](https://github.com/sonic-net/sonic-buildimage/pull/19275). Please use the image with the fix to run the test.

Hi @bingwang-ms , 

I see that PR #19275 was merged in June. The image I'm using was built on July 10, which already includes the fix, but I still encounter the issue. Could you please help check it, thanks!

**Comment by yxieca** [comment]
@weiguo-nvidia can you share the link of the image you used? Or test again with a latest image?
