### ISSUE TITLE
[Bug]: test_ecmp_hash_seed_value test fails with IndexError

### ISSUE THREAD

**Issue by dayouliu1** [sonic-net/sonic-mgmt#14829]
### Issue Description

test_ecmp_hash_seed_value will fail when loading the check_dut_asic_type fixture

### Results you see

test_ecmp_hash_seed_value will fail on setup with `IndexError: Bad index 'None' type <class 'NoneType'>` when loading check_dut_asic_type fixture

### Results you expected to see

Expect to see no failure

### Is it platform specific

generic

### Relevant log output

```shell
failed on setup with "IndexError: Bad index 'None' type <class 'NoneType'>"
==========================
request = <SubRequest 'check_dut_asic_type' for <Function test_ecmp_hash_seed_value[dut]>>
duthosts = [<MultiAsicSonicHost dut>], rand_one_dut_hostname = None

    @pytest.fixture(scope="function")
    def check_dut_asic_type(request, duthosts, rand_one_dut_hostname):
>       duthost = duthosts[rand_one_dut_hostname]

duthosts   = [<dut>]
rand_one_dut_hostname = None
request    = <SubRequest 'check_dut_asic_type' for <Function test_ecmp_hash_seed_value[dut]>>

common/plugins/custom_fixtures/check_dut_asic_type.py:7:
```

### Output of `show version`

202405

**Comment by ZhaohuiS** [comment]
it's fixed by https://github.com/sonic-net/sonic-mgmt/pull/14935#event-14583285299

https://github.com/sonic-net/sonic-mgmt/pull/14075 was forgot to do cherry pick into 202405

**Comment by dayouliu1** [comment]
I see that https://github.com/sonic-net/sonic-mgmt/pull/14935 changed the fixture dependencies in check_dut_asic_type, but the underlying problem is still present and will pop up again if there is another instance where rand_one_dut_hostname or selected_rand_dut is added dynamically.

**Comment by ZhaohuiS** [comment]
@dayouliu1 would you please come up a fix PR?

**Comment by dayouliu1** [comment]
This is the fix: https://github.com/sonic-net/sonic-mgmt/pull/14830
